# +----------------------------------------------------------------------------------------------------+
# |                                                                                                    |
# | This is the main configuration file used by MkDocs to generate the documentation from Markdown     |
# | files.                                                                                             |
# | It contains a lot of configuration options but at its core is only the 'site_name' option required |
# | with every other option being optional.                                                            |
# |                                                                                                    |
# |----------------------------------------------- NOTE -----------------------------------------------|
# |                                                                                                    |
# | While this configuration file contains a lot of comments will not all options be explained in      |
# | detail.                                                                                            |
# | Instead will you often find "Read More" links pointing to the official documentation of MkDocs     |
# | to allow further reading on these settings.                                                        |
# |                                                                                                    |
# | Also, this file will ONLY cover MkDocs itself. For a configuration example using the Material for  |
# | MkDocs theme, check the "material.yml" file, which inherits from this file itself.                 |
# | Options are categorized and listed in order of appearance within MkDocs' Configuration doc page.   |
# |                                                                                                    |
# |-------------------------------------------- DISCLAIMER --------------------------------------------|
# |                                                                                                    |
# | I do not guarantee for these files to be up-to-date nor maintained. Please make sure to first      |
# | check for any major changes introduced by MkDocs or any of the themes, extensions or plugins used. |
# |                                                                                                    |
# | File last updated: 27th of Sep 2023                                                                |
# |                                                                                                    |
# +----------------------------------------------------------------------------------------------------+

# +----------------------------------------------------------------------------------------------------+
# |                                         PROJECT INFORMATION                                        |
# |                                                                                                    |
# | The below options are used to defined various things for the project touse and display such as the |
# | Site name, Site author and canonical URL.                                                          |
# | Note that ONLY the "site_name" is required with every other option being optional.                 |
# |                                                                                                    |
# | Read More:                                                                                         |
# |   https://www.mkdocs.org/user-guide/configuration/#project-information                             |
# |                                                                                                    |
# | Settings:                                                                                          |
# | - site_name                                                                                        |
# |     The only required option for the mkdocs.yml file to be valid.                                  |
# |     Defines the main title used for the documentation (i.e. within browser tabs or the docs page   |
# |     depending on the theme used).                                                                  |
# |                                                                                                    |
# | - site_url                                                                                         |
# |     Defines the canonical URL under which you can find the built documentation on the internet.    |
# |     The URL will be used within a "link" meta tag with the "canonical" URL to the head section of  |
# |     each HTML page.                                                                                |
# |     Make sure to also include any subdirectories in the URL should your page be hosted under it.   |
# |     If you're publishing the docs on GitHub while not using a custom domain or subdomain, common   |
# |     URL formats are either https://<username>.github.io or https://<username>.github.io/<repo>     |
# |                                                                                                    |
# | - repo_url                                                                                         |
# |     Defines the URL to the repository where you have the source of this documentation.             |
# |     When set will provide a link to the repository on each page.                                   |
# |     The URL may also be used with the "edit_uri" appendet to it to provide a edit link for a page. |
# |                                                                                                    |
# | - repo_name                                                                                        |
# |     Defines the name to display for the "repo_url" link on each page.                              |
# |                                                                                                    |
# | - edit_uri                                                                                         |
# |     The path from the repo_url to the docs directory.                                              |
# |     As an example, setting "edit/master/docs/" as edit_uri while using                             |
# |     https://github.com/Andre601/mkdocs-template will result in the URL                             |
# |     https://github.com/Andre601/mkdocs-template/edit/master/docs/. Any page path will be appendet. |
# |     An absolute URL can also be defined by just providing the full URL (with http(s)://).          |
# |     For further customization (i.e. include file path in-between the edit path) use the            |
# |     edit_uri_template option instead.                                                              |
# |                                                                                                    |
# | - edit_uri_template                                                                                |
# |     DON'T SET THIS OPTION ALONGSIDE edit_uri. THEY ARE MUTUALLY EXCLUSIVE.                         |
# |     Defines the path to the docs_dir in a repository which gets appended to the repo_url itself.   |
# |     This option uses Python format String with the following options being available:              |
# |       -  {path}      - The full path of a file relative to docs dir (i.e. foo/bar.md)              |
# |       - {path_noext} - Same as {path} but without the file extension (i.e. foo/bar)                |
# |     There is also a !q conversion flag available to percent-encode the path.                       |
# |     For example, {path!q} may return foo%2Fbar.md                                                  |
# |                                                                                                    |
# | - site_description                                                                                 |
# |     Defines the description of the site, which is included as a description meta tag in the        |
# |     header.                                                                                        |
# |                                                                                                    |
# | - site_author                                                                                      |
# |     Defines the site author which is included as a meta tag in the header.                         |
# |                                                                                                    |
# | - copyright                                                                                        |
# |     Allows you to define the copyright of a site to be included by the theme.                      |
# |     Depending on how a theme handles this option will it be treated as HTML, meaning you have to   |
# |     consider cases of escaping certain content (i.e. < and >) and use specific shortcodes like     |
# |     &copy; for the copyright symbol.                                                               |
# |                                                                                                    |
# | - remote_branch                                                                                    |
# |     The remote target branch used by MkDocs to push the built docs towards when using gh-deploy.   |
# |     For GitHub this usually should be gh-pages (The default).                                      |
# |     This option can be overriden by a command line option.                                         |
# |                                                                                                    |
# | - remote_origin                                                                                    |
# |     The name of the remote repository to push towards.                                             |
# |     By default git names the remote "origin" which is also the default for MkDocs.                 |
# |     This option can be overriden by a command line option.                                         |
# |                                                                                                    |
# +----------------------------------------------------------------------------------------------------+

site_name: 'MkDocs Template'
site_url: 'https://docs.andre601.ch/mkdocs-template'

repo_url: 'https://github.com/Andre601/mkdocs-template'
repo_name: 'Andre601/mkdocs-template'

edit_uri: 'blob/master/docs/'
#edit_uri_template: 'blob/master/docs/{path}' # Equal to edit_uri

site_description: 'A template for creating MkDocs documentation.'
site_author: 'Andre_601'

copyright: '&copy; Andre_601' # The text is treated as HTML, so you have to escape certain characters.

remote_branch: 'gh-pages'
remote_name: 'origin'

# +----------------------------------------------------------------------------------------------------+
# |                                        DOCUMENTATION LAYOUT                                        |
# |                                                                                                    |
# | These are the settings used to define the overall layout of your documentation such as the         |
# | navigation, what not to include in it or the build process itself and how MkDocs should react on   |
# | encountering certain situation related to the nav and layout.                                      |
# |                                                                                                    |
# | Read More:                                                                                         |
# |  https://www.mkdocs.org/user-guide/configuration/#documentation-layout                             |
# |                                                                                                    |
# | Settings:                                                                                          |
# | - nav                                                                                              |
# |     Defines the navigation to display in the configuration.                                        |
# |     Multiple forms of formatting can be included here including the direct path to a file, the     |
# |     path to a file prefixed by a title, a absolute URL or a section containing nested entries of   |
# |     former mentioned options.                                                                      |
# |                                                                                                    |
# | - exclude_docs                                                                                     |
# |     String option that defines files and folders relative to the docs_dir to exclude from when     |
# |     building the effective docs (Running "mkdocs build" or "mkdocs gh-deploy").                    |
# |     This option follows the .gitignore pattern format. Read more about it here:                    |
# |     https://git-scm.com/docs/gitignore#_pattern_format                                             |
# |                                                                                                    |
# | -                                                                                                  |
# |                                                                                                    |
# |                                                                                                    |
# |                                                                                                    |
# |                                                                                                    |
# +----------------------------------------------------------------------------------------------------+
nav:
  - Home: index.md
  - Themes:
    - 'Material for MkDocs': 'themes/material.md'

#exclude_docs: |
#  drafts/







